const instagramAndTelegramConversations = [
  {
    id: "conv_ig_1",
    channel: "instagram",
    externalConversationId: "ig_2001",
    customer: {
      id: "cust_ig_1",
      name: "Laura Pérez",
      externalUserId: "ig_user_2001",
      phone: null,
    },
    lead: {
      status: "pending",
      source: "instagram",
      interest: "asesoramiento contable",
      priority: "alta",
    },
    subject: "Primera consulta contable",
    lastMessage: "Necesito asesoramiento para monotributo y facturación.",
    status: "pending",
    updatedAt: "2026-03-12T10:25:00Z",
    messages: [
      {
        id: "msg_ig_1",
        direction: "inbound",
        from: "customer",
        text: "Hola, necesito asesoramiento contable.",
        sentAt: "2026-03-12T10:20:00Z",
        channel: "instagram",
      },
      {
        id: "msg_ig_2",
        direction: "inbound",
        from: "customer",
        text: "Necesito asesoramiento para monotributo y facturación.",
        sentAt: "2026-03-12T10:25:00Z",
        channel: "instagram",
      },
    ],
  },
  {
    id: "conv_tg_1",
    channel: "telegram",
    externalConversationId: "tg_3001",
    customer: {
      id: "cust_tg_1",
      name: "Julián Gómez",
      externalUserId: "tg_user_3001",
      phone: null,
    },
    lead: {
      status: "interested",
      source: "telegram",
      interest: "Toyota Corolla",
      priority: "alta",
    },
    subject: "Consulta por Toyota Corolla",
    lastMessage: "¿Sigue disponible? ¿Tomás permuta?",
    status: "interested",
    updatedAt: "2026-03-12T10:15:00Z",
    messages: [
      {
        id: "msg_tg_1",
        direction: "inbound",
        from: "customer",
        text: "Hola, ¿sigue disponible el Toyota Corolla?",
        sentAt: "2026-03-12T10:10:00Z",
        channel: "telegram",
      },
      {
        id: "msg_tg_2",
        direction: "inbound",
        from: "customer",
        text: "¿Tomás permuta?",
        sentAt: "2026-03-12T10:15:00Z",
        channel: "telegram",
      },
    ],
  },
];
